/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
static yyconst short int yy_accept[435] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       84,   83,   41,   39,   83,   78,   83,   82,   82,   79,
       82,   82,   82,   82,   82,   77,   77,   82,   82,   82,
       82,   82,   76,   76,   76,   76,   82,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   82,   40,   42,   47,   49,   45,
       50,   51,   83,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       41,   71,    0,   52,   60,   62,   66,   56,   54,   55,

       75,   67,   57,    0,    0,   77,   77,   77,   77,   77,
        0,   77,   74,   73,   68,   70,   69,   72,   61,   76,
       76,   76,   76,   64,   76,   23,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   34,   76,
       11,   16,   76,   76,   76,   35,   76,   76,   76,   76,
       76,   76,   76,   63,   40,   42,   46,   44,   48,   45,
       43,   50,    0,    0,    0,    1,    1,    1,    1,    1,
        0,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,   80,   59,   58,    0,    0,
       77,   77,   77,   77,    0,   77,   65,   53,   76,   76,
       76,   18,   76,   76,   76,   76,   76,   76,   76,    2,
       28,   76,   76,   76,   76,   20,   76,   76,   76,   76,
       76,   76,   30,   76,   76,   76,   22,   76,   76,   76,
       81,    0,    0,    1,    1,    1,    1,    0,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    0,   80,    0,    0,    0,   77,   77,   76,    9,

       13,   76,   76,   76,   76,   38,   76,   76,   33,    6,
       76,   76,   24,   76,   76,   76,   76,   76,    7,   76,
       76,   76,   31,   76,    0,    0,    0,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    0,    0,    0,   77,    3,
       76,   32,    4,    8,   14,   76,   76,   76,   76,   76,
       76,   37,   76,   12,   76,   26,   36,    0,    0,    0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    0,

        0,   27,   76,   10,   76,   29,    5,   21,   76,   17,
        0,    0,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    0,   76,   15,   76,    0,    1,    1,    1,   19,
       25,    1,    1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,    1,   28,   29,   30,   29,   29,   31,   32,
       33,   33,   33,   34,   33,   33,   33,   35,   36,   33,
       33,   33,   33,   37,   33,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   34,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   33,   63,   64,
       65,   33,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    6,    7,    6,    6,    6,    6,    1,    8,
        1,    1,    6,    5,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[455] =
    {   0,
        0,  842,   67,   68,   69,   72,  837,  836,  112,  839,
      840,  845,   74,  845,  813,  832,    0,  811,  810,  845,
      845,   64,  809,   54,   65,  163,  169,  808,   59,  807,
       60,  806,    0,  787,  773,  770,  802,   32,  768,   45,
      778,   39,  135,  771,   45,  780,  779,  765,  762,  776,
       62,  760,   45,  766,  791,  193,    0,  845,  845,  199,
        0,  845,  810,  845,  809,  845,  845,  192,  204,    0,
      770,  756,  753,  173,  752,  162,  762,  177,  188,  755,
      202,  764,  763,  749,  746,  760,  198,  744,  192,  750,
      194,  845,  795,    0,  845,  845,  774,  845,  845,  845,

      845,  773,  845,  239,  246,  234,  250,    0,  253,  269,
        0,  845,  845,  772,  845,  845,  845,  771,  845,    0,
      742,  739,  732,  845,  746,  150,  748,  743,  730,  745,
      732,  227,  233,  741,  730,  726,  727,  726,    0,  724,
        0,    0,  726,  719,  222,    0,  719,  726,  716,  711,
      723,  713,  725,  845,  230,    0,  845,  845,  845,  845,
      845,    0,  766,  275,  285,  279,  289,    0,  292,  308,
        0,  845,    0,  717,  714,  707,  721,  255,  723,  718,
      705,  720,  707,  282,  272,  716,  705,  701,  702,  701,
        0,  699,    0,    0,  701,  694,  282,    0,  694,  701,

      691,  686,  698,  688,  700,  744,  845,  845,  327,  333,
      302,  340,    0,  349,    0,  358,  845,  845,  686,  697,
      696,    0,  695,  686,  689,  696,  691,  678,  676,    0,
        0,  687,  687,  686,  689,    0,  676,  678,  658,  662,
      649,  637,    0,  623,  607,  597,    0,  592,  593,  584,
      845,  365,  378,  315,  369,    0,  382,    0,  401,  577,
      578,  551,    0,  550,  541,  544,  551,  545,  532,  530,
        0,    0,  540,  535,  525,  524,    0,  512,  520,  501,
      510,  506,  493,    0,  486,  477,  472,    0,  477,  479,
      475,    0,  524,  408,  424,    0,  443,  432,  478,    0,

        0,  466,  465,  448,  454,    0,  446,  452,    0,    0,
      445,  441,    0,  450,  425,  433,  427,  404,    0,  412,
      399,  402,    0,  402,  448,  454,    0,  467,  471,  400,
        0,    0,  388,  394,  377,  384,    0,  376,  382,    0,
        0,  375,  378,    0,  387,  366,  377,  368,  361,    0,
      366,  352,  362,    0,  361,  478,    0,  494,  498,    0,
      346,    0,    0,    0,    0,  350,  344,  340,  339,  330,
      332,    0,  327,    0,  310,    0,    0,  502,    0,  519,
      523,    0,  304,    0,    0,    0,    0,  307,  301,  303,
      297,  284,  297,    0,  291,    0,  262,    0,    0,  540,

      529,    0,  230,    0,  217,    0,    0,    0,  235,    0,
      550,  556,    0,  202,    0,  185,    0,    0,    0,  204,
        0,  560,  170,    0,  153,  566,  156,    0,   57,    0,
        0,    0,    0,  845,  600,  608,  616,  624,  628,  635,
      642,  645,   99,  652,   93,  660,  668,  676,  684,  692,
      700,  708,  716,  724
    } ;

static yyconst short int yy_def[455] =
    {   0,
      434,    1,  435,  435,  436,  436,  437,  437,  434,    9,
      434,  434,  434,  434,  434,  434,  438,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  439,  439,  439,  439,  434,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  434,  434,  440,  434,  434,  434,
      441,  434,  434,  434,  434,  434,  434,  434,  434,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      434,  434,  434,  438,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  443,  434,  434,
      444,  434,  434,  434,  434,  434,  434,  434,  434,  439,
      439,  439,  439,  434,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  434,  434,  440,  434,  434,  434,  434,
      434,  441,  434,  434,  434,  434,  434,  445,  434,  434,
      446,  434,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,

      442,  442,  442,  442,  442,  447,  434,  434,  434,  434,
      434,  434,  443,  434,  448,  434,  434,  434,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      434,  434,  434,  434,  434,  445,  434,  449,  434,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  450,  447,  434,  434,  451,  434,  434,  439,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  434,  434,  452,  434,  434,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  434,  453,  434,  434,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  434,  454,  434,
      434,  442,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  442,  442,  442,  442,  442,  442,  442,  442,  434,

      434,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      434,  434,  442,  442,  442,  442,  442,  442,  442,  442,
      442,  434,  439,  439,  439,  434,  442,  442,  442,  439,
      439,  442,  442,    0,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434
    } ;

static yyconst short int yy_nxt[915] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   18,   19,   20,
       21,   21,   22,   23,   21,   24,   21,   25,   26,   27,
       27,   27,   28,   21,   29,   30,   31,   32,   33,   33,
       33,   34,   33,   33,   35,   33,   36,   33,   21,   12,
       21,   37,   33,   38,   39,   40,   41,   42,   43,   44,
       33,   45,   33,   46,   47,   48,   49,   50,   51,   33,
       52,   33,   53,   33,   54,   21,   55,   21,   21,   58,
       58,   58,   59,   59,   58,   91,   97,   91,   62,  100,
      101,   62,  102,  114,  115,  117,  118,  125,  129,   98,
      103,  126,  133,  139,  127,  151,  152,  256,  130,  140,

      141,  131,  134,  213,  142,  148,   60,   60,   60,  149,
      433,   60,   12,   13,   64,   13,   15,   65,   17,   18,
       19,   66,   67,   67,   22,   23,   21,   24,   21,   25,
       68,   69,   69,   69,   28,   21,   29,   30,   31,   32,
       70,   70,   70,   71,   70,   70,   72,   70,   73,   70,
       67,   12,   67,   37,   70,   74,   75,   76,   77,   78,
       79,   80,   70,   81,   70,   82,   83,   84,   85,   86,
       87,   70,   88,   70,   89,   70,   90,   67,   55,   67,
       21,  104,  105,  105,  105,  109,  135,  110,  110,  110,
      110,  136,  106,  137,  155,   91,   91,   91,  107,  111,

      108,  157,  112,  432,  158,  181,  431,  106,  159,  223,
      164,  165,  165,  165,  224,  182,  111,  430,  183,  107,
      169,  166,  170,  170,  170,  170,  108,  167,  177,  168,
      185,  155,  178,   91,  171,  179,  166,  172,  160,  187,
      186,  200,  203,  204,  188,  201,  189,  429,  167,  428,
      191,  171,  211,  211,  161,  168,  192,  193,  209,  209,
      209,  194,  109,  427,  210,  210,  210,  210,  212,  212,
      212,  214,  214,  214,  214,  230,  111,  242,  425,  112,
      231,  424,  243,  215,  232,  109,  112,  110,  110,  110,
      110,  423,  233,  111,  252,  252,  252,  254,  254,  111,

      215,  169,  112,  253,  253,  253,  253,  255,  255,  255,
      257,  257,  257,  257,  264,  171,  111,  421,  172,  265,
      211,  211,  258,  273,  169,  172,  170,  170,  170,  170,
      271,  274,  171,  254,  254,  272,  420,  283,  171,  258,
      419,  172,  284,  294,  418,  295,  295,  295,  295,  109,
      417,  210,  210,  210,  210,  171,  416,  296,  212,  212,
      212,  415,  414,  111,  413,  410,  112,  214,  214,  214,
      214,  298,  409,  298,  296,  408,  214,  214,  214,  214,
      111,  325,  112,  326,  326,  326,  326,  255,  255,  255,
      407,  112,  406,  405,  169,  327,  253,  253,  253,  253,

      257,  257,  257,  257,  404,  403,  402,  399,  171,  398,
      397,  172,  327,  396,  329,  172,  329,  395,  394,  257,
      257,  257,  257,  393,  392,  171,  356,  356,  356,  356,
      391,  390,  389,  388,  172,  387,  386,  385,  357,  384,
      294,  112,  295,  295,  295,  295,  383,  382,  377,  376,
      214,  214,  214,  214,  296,  357,  359,  375,  359,  374,
      373,  214,  214,  214,  214,  112,  378,  378,  378,  378,
      325,  296,  326,  326,  326,  326,  112,  372,  379,  371,
      381,  172,  381,  370,  327,  257,  257,  257,  257,  257,
      257,  257,  257,  369,  368,  379,  356,  356,  356,  356,

      172,  327,  367,  366,  172,  365,  364,  401,  363,  401,
      362,  112,  356,  356,  356,  356,  214,  214,  214,  214,
      378,  378,  378,  378,  361,  360,  293,  112,  355,  354,
      353,  112,  412,  352,  412,  172,  351,  378,  378,  378,
      378,  257,  257,  257,  257,  350,  349,  356,  356,  356,
      356,  348,  172,  422,  347,  422,  172,  346,  356,  356,
      356,  356,  112,  426,  345,  426,  344,  343,  378,  378,
      378,  378,  342,  112,  378,  378,  378,  378,  356,  356,
      356,  356,  341,  172,  378,  378,  378,  378,  340,  172,
      339,  338,  337,  112,  336,  335,  334,  333,  332,  172,

       57,   57,   57,   57,   57,   57,   57,   57,   61,   61,
       61,   61,   61,   61,   61,   61,   12,   12,   12,   12,
       12,   12,   12,   12,   94,  331,   94,   94,   94,   94,
       94,   94,  120,  120,  120,  156,  330,  324,  156,  156,
      156,  156,  162,  323,  162,  322,  162,  162,  162,  173,
      173,  173,  216,  216,  216,  216,  216,  216,  321,  216,
      259,  259,  259,  259,  259,  259,  320,  259,  292,  292,
      292,  292,  292,  292,  292,  292,  297,  297,  297,  297,
      297,  297,  319,  297,  328,  328,  328,  328,  328,  328,
      318,  328,  293,  293,  317,  293,  293,  293,  293,  293,

      358,  358,  358,  358,  358,  358,  316,  358,  380,  380,
      380,  380,  380,  380,  315,  380,  400,  400,  400,  400,
      400,  400,  314,  400,  411,  411,  411,  411,  411,  411,
      313,  411,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  293,  291,  290,  289,
      288,  287,  286,  285,  282,  281,  280,  279,  278,  277,
      276,  275,  270,  269,  268,  267,  266,  263,  262,  261,
      260,  251,  250,  249,  248,  247,  246,  245,  244,  241,
      240,  239,  238,  237,  236,  235,  234,  229,  228,  227,
      226,  225,  222,  221,  220,  219,  218,  217,  208,  207,

      206,  205,  202,  199,  198,  197,  196,  195,  190,  184,
      180,  176,  175,  174,   93,  163,  154,  153,  150,  147,
      146,  145,  144,  143,  138,  132,  128,  124,  123,  122,
      121,  119,  116,  113,   99,   96,   95,   93,   92,  434,
       56,   63,   63,   56,   11,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434
    } ;

static yyconst short int yy_chk[915] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    3,    4,    6,   13,   22,   13,    5,   24,
       24,    6,   25,   29,   29,   31,   31,   38,   40,   22,
       25,   38,   42,   45,   38,   53,   53,  445,   40,   45,

       45,   40,   42,  443,   45,   51,    3,    4,    5,   51,
      429,    6,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,   26,   26,   26,   26,   27,   43,   27,   27,   27,
       27,   43,   26,   43,   56,   91,   56,   91,   26,   27,

       26,   60,   27,  427,   60,   76,  425,   26,   60,  126,
       68,   68,   68,   68,  126,   76,   27,  423,   76,   26,
       69,   68,   69,   69,   69,   69,   26,   68,   74,   68,
       78,  155,   74,  155,   69,   74,   68,   69,   60,   79,
       78,   87,   89,   89,   79,   87,   79,  420,   68,  416,
       81,   69,  106,  106,   60,   68,   81,   81,  104,  104,
      104,   81,  105,  414,  105,  105,  105,  105,  107,  107,
      107,  109,  109,  109,  109,  132,  105,  145,  409,  105,
      132,  405,  145,  109,  133,  110,  109,  110,  110,  110,
      110,  403,  133,  105,  164,  164,  164,  166,  166,  110,

      109,  165,  110,  165,  165,  165,  165,  167,  167,  167,
      169,  169,  169,  169,  178,  165,  110,  397,  165,  178,
      211,  211,  169,  185,  170,  169,  170,  170,  170,  170,
      184,  185,  165,  254,  254,  184,  395,  197,  170,  169,
      393,  170,  197,  209,  392,  209,  209,  209,  209,  210,
      391,  210,  210,  210,  210,  170,  390,  209,  212,  212,
      212,  389,  388,  210,  383,  375,  210,  214,  214,  214,
      214,  216,  373,  216,  209,  371,  216,  216,  216,  216,
      210,  252,  214,  252,  252,  252,  252,  255,  255,  255,
      370,  216,  369,  368,  253,  252,  253,  253,  253,  253,

      257,  257,  257,  257,  367,  366,  361,  355,  253,  353,
      352,  253,  252,  351,  259,  257,  259,  349,  348,  259,
      259,  259,  259,  347,  346,  253,  294,  294,  294,  294,
      345,  343,  342,  339,  259,  338,  336,  335,  294,  334,
      295,  294,  295,  295,  295,  295,  333,  330,  324,  322,
      298,  298,  298,  298,  295,  294,  297,  321,  297,  320,
      318,  297,  297,  297,  297,  298,  325,  325,  325,  325,
      326,  295,  326,  326,  326,  326,  297,  317,  325,  316,
      328,  325,  328,  315,  326,  328,  328,  328,  328,  329,
      329,  329,  329,  314,  312,  325,  356,  356,  356,  356,

      328,  326,  311,  308,  329,  307,  305,  358,  304,  358,
      303,  356,  358,  358,  358,  358,  359,  359,  359,  359,
      378,  378,  378,  378,  302,  299,  293,  358,  291,  290,
      289,  359,  380,  287,  380,  378,  286,  380,  380,  380,
      380,  381,  381,  381,  381,  285,  283,  401,  401,  401,
      401,  282,  380,  400,  281,  400,  381,  280,  400,  400,
      400,  400,  401,  411,  279,  411,  278,  276,  411,  411,
      411,  411,  275,  400,  412,  412,  412,  412,  422,  422,
      422,  422,  274,  411,  426,  426,  426,  426,  273,  412,
      270,  269,  268,  422,  267,  266,  265,  264,  262,  426,

      435,  435,  435,  435,  435,  435,  435,  435,  436,  436,
      436,  436,  436,  436,  436,  436,  437,  437,  437,  437,
      437,  437,  437,  437,  438,  261,  438,  438,  438,  438,
      438,  438,  439,  439,  439,  440,  260,  250,  440,  440,
      440,  440,  441,  249,  441,  248,  441,  441,  441,  442,
      442,  442,  444,  444,  444,  444,  444,  444,  246,  444,
      446,  446,  446,  446,  446,  446,  245,  446,  447,  447,
      447,  447,  447,  447,  447,  447,  448,  448,  448,  448,
      448,  448,  244,  448,  449,  449,  449,  449,  449,  449,
      242,  449,  450,  450,  241,  450,  450,  450,  450,  450,

      451,  451,  451,  451,  451,  451,  240,  451,  452,  452,
      452,  452,  452,  452,  239,  452,  453,  453,  453,  453,
      453,  453,  238,  453,  454,  454,  454,  454,  454,  454,
      237,  454,  235,  234,  233,  232,  229,  228,  227,  226,
      225,  224,  223,  221,  220,  219,  206,  205,  204,  203,
      202,  201,  200,  199,  196,  195,  192,  190,  189,  188,
      187,  186,  183,  182,  181,  180,  179,  177,  176,  175,
      174,  163,  153,  152,  151,  150,  149,  148,  147,  144,
      143,  140,  138,  137,  136,  135,  134,  131,  130,  129,
      128,  127,  125,  123,  122,  121,  118,  114,  102,   97,

       93,   90,   88,   86,   85,   84,   83,   82,   80,   77,
       75,   73,   72,   71,   65,   63,   55,   54,   52,   50,
       49,   48,   47,   46,   44,   41,   39,   37,   36,   35,
       34,   32,   30,   28,   23,   19,   18,   16,   15,   11,
       10,    8,    7,    2,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,

      434,  434,  434,  434,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "index.l"
#define INITIAL 0
#define STRINGG 1

#define SINGLESTRINGG 2

#define MLCOMMENTSTATE 3

#define newline 4

#line 7 "index.l"
    #include <stdio.h>
    #include <stdlib.h>
    #include <ctype.h>
    #include <math.h>
    #include <string.h>
    #include "y.tab.h"

    int yylineno = 1;
    int numberofindent = 0;
    int levels = 0;
    char* string_literal_value = NULL;
#line 734 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 48 "index.l"


#line 891 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 435 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 845 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 51 "index.l"
{

    yyless(0);
    if(levels > 1){
        // BEGIN(INITIAL);
        levels--;
        return DEDENT;
    }
    else if(levels==1){
        levels--;
        BEGIN(INITIAL);
        numberofindent = 0;
        return DEDENT;
    }
    else
        BEGIN(INITIAL);
    // if(numberofindent != 0){
    // }
}
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 71 "index.l"
{return DEF;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "index.l"
{return FALSEE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 73 "index.l"
{return AWAIT;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 74 "index.l"
{return IMPORT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 75 "index.l"
{return ELSE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 76 "index.l"
{return PASS;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 77 "index.l"
{return BREAK;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 78 "index.l"
{return NONE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "index.l"
{return EXCEPT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 80 "index.l"
{return IN;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 81 "index.l"
{return RAISE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 82 "index.l"
{return TRUEE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 83 "index.l"
{return CLASS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 84 "index.l"
{return FINALLY;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 85 "index.l"
{return IS;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 86 "index.l"
{return RETURN;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 87 "index.l"
{return AND;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 88 "index.l"
{return CONTINUE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 89 "index.l"
{return FOR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 90 "index.l"
{return LAMBDA;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 91 "index.l"
{return TRY;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 92 "index.l"
{return AS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 93 "index.l"
{return FROM;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 94 "index.l"
{return NONLOCAL;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 95 "index.l"
{return WHILE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 96 "index.l"
{return ASSERT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 97 "index.l"
{return DEL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 98 "index.l"
{return GLOBAL;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 99 "index.l"
{return NOT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 100 "index.l"
{return WITH;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 101 "index.l"
{return ASYNC;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 102 "index.l"
{return ELIF;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 103 "index.l"
{return IF;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 104 "index.l"
{return OR;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 105 "index.l"
{return YIELD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 106 "index.l"
{return MATCH;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "index.l"
{return CASE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 109 "index.l"
{
                                yylineno++;
                                BEGIN(newline);
                                return NEWLINE;
                            }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 115 "index.l"
{
                                int dis = yyleng - numberofindent;
                                numberofindent = yyleng;
                                if(dis > 0)
                                {
                                    BEGIN(INITIAL);
                                    levels++;
                                    return INDENT;
                                }
                                else if(dis < 0)
                                {
                                    BEGIN(INITIAL);
                                    levels--;
                                    return DEDENT;
                                }
                                else
                                    BEGIN(INITIAL);
                            }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 134 "index.l"
{}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 136 "index.l"
{
                                string_literal_value = realloc(string_literal_value, strlen(string_literal_value) + yyleng + 1);
                                strcat(string_literal_value, yytext);
                            }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 141 "index.l"
{
                                string_literal_value = realloc(string_literal_value, strlen(string_literal_value) + 1);
                                strcat(string_literal_value, "\n");
                                printf("new line\n");
                            }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 147 "index.l"
{
                                        string_literal_value = realloc(string_literal_value, strlen(string_literal_value) +1);
                                        strcat(string_literal_value, "\"");
                                    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 152 "index.l"
{
                                        string_literal_value = realloc(string_literal_value, strlen(string_literal_value) + 1);
                                        strcat(string_literal_value, "\\");
                                        printf("backslash\n");
                                    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 158 "index.l"
{
                                        string_literal_value = realloc(string_literal_value, strlen(string_literal_value) + 1);
                                        strcat(string_literal_value, "");
                                        printf("backslash gone with new line\n");
                                    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 164 "index.l"
{
                                        string_literal_value = realloc(string_literal_value, strlen(string_literal_value) + 1);
                                        strcat(string_literal_value, "");
                                        printf("Error\n");
                                    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 170 "index.l"
{
                                        string_literal_value = realloc(string_literal_value, strlen(string_literal_value) + 1);
                                        strcat(string_literal_value, "'");
                                        printf("single quotation\n");
                                    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 176 "index.l"
{
                                BEGIN(INITIAL);
                                printf("the end of STate: %s\n", string_literal_value);
                            }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 181 "index.l"
{
                                string_literal_value = realloc(string_literal_value, strlen(string_literal_value) + yyleng + 1);
                                strcat(string_literal_value, yytext);
                            }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 186 "index.l"
{
                                BEGIN(INITIAL);
                                printf("the end of STate: %s\n", string_literal_value);
                            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 191 "index.l"
{printf("comment = %s in line = %d\n",yytext,yylineno);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 193 "index.l"
{return ASSIGNRIGHTSHIFT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 195 "index.l"
{return ASSIGNADD;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 197 "index.l"
{return ASSIGNMINUS;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 199 "index.l"
{return ASSIGNMUL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 201 "index.l"
{return ASSIGNDIVIDE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 203 "index.l"
{return ASSIGNINTDIVIDE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 205 "index.l"
{return ASSIGNPOWER;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 207 "index.l"
{return ASSIGNMODULUS;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 209 "index.l"
{return ASSIGNARRMUL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 211 "index.l"
{return ASSIGNANDBIT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 213 "index.l"
{return ASSIGNORBIT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 215 "index.l"
{return ASSIGNXORBIT;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 217 "index.l"
{return ASSIGNLEFTSHIFT;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 219 "index.l"
{return POWER;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 221 "index.l"
{return INTDIVIDE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 223 "index.l"
{return SME;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 225 "index.l"
{return GTE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 227 "index.l"
{return EQUAL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 229 "index.l"
{return NOTEQUAL;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 231 "index.l"
{return RIGHTSHIFT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 233 "index.l"
{return LEFTSHIFT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 235 "index.l"
{return ASSIGN;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 237 "index.l"
{return FN;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 239 "index.l"
{return IDENTIFIER;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 241 "index.l"
{return NUMBER;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 243 "index.l"
{
                    BEGIN(STRINGG);
                    string_literal_value = strdup("");  // Initialize the string literal value
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 248 "index.l"
{
                    BEGIN(SINGLESTRINGG);
                    string_literal_value = strdup("");  // Initialize the string literal value
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 253 "index.l"
{
                        BEGIN(MLCOMMENTSTATE);
                        printf("multiline comment = %s\n",yytext,yylineno);
                    }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 258 "index.l"
{
                            BEGIN(INITIAL);
                            printf("End of multiline comment = %s in line = %d\n",yytext,yylineno);
                            }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 263 "index.l"
{return yytext[0];}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 265 "index.l"
ECHO;
	YY_BREAK
#line 1478 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRINGG):
case YY_STATE_EOF(SINGLESTRINGG):
case YY_STATE_EOF(MLCOMMENTSTATE):
case YY_STATE_EOF(newline):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 435 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 435 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 434);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 265 "index.l"


// void main(int argc, char **argv)
// {
//     if (argc > 1){
//         for(int i = 0; i < argc; i++)
//             printf("value of argv[%d] = %s\n\n",i,argv[i]);
//         yyin = fopen(argv[1], "r");
//     }
//     else
//         yyin = stdin;
//     yylex();
// }
/*yywrap is called whenever lex reaches an end-of-file we must define this function because yylex() need it*/
int yywrap(){
    exit(0);
}